/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/guitar_src/scene.gltf
Author: YieldingMist206 (https://sketchfab.com/YieldingMist206)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fender-stratocaster-guitar-blue-96a79610434f43b2ac2a09a636afc5d4
Title: Fender Stratocaster Guitar Blue
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Guitar = forwardRef(({ children, ...props }, ref) => {
  const { nodes, materials } = useGLTF('./Guitar_src/scene.gltf')


  return (
    <group ref={ref} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100}>
            <mesh {...props} castShadow geometry={nodes.Guitar_Guitar_0.geometry} material={materials.Guitar} />
            <mesh geometry={nodes.BezierCurve001_Guitar_0.geometry} material={materials.Guitar} />
            {children}
          </group>
          <group position={[10.75, 15.02, 185.12]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Strings_Guitar_0.geometry} material={materials.Guitar} />
            <mesh geometry={nodes.Cube_Guitar_0.geometry} material={materials.Guitar} position={[-0.11, 0.08, -0.15]} />
          </group>
          <mesh geometry={nodes.Buttons_Buttons_0.geometry} material={materials.Buttons} position={[9.2, -29.3, 156.7]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('./Guitar_src/scene.gltf')
